services:
  - type: web
    name: zaytona-mcp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: fastmcp run server.py -t sse
    envVars:
      - key: PORT
        value: 10000
