from tafsir.adapters.base import TafsirAdapter
from tafsir.adapters.quran_db import QuranDBAdapter
from tafsir.adapters.jalalayn import JalalaynAdapter
from tafsir.adapters.extended import ExtendedTafsirAdapter
from tafsir.models import TafsirSource

ADAPTERS: dict[TafsirSource, TafsirAdapter] = {
    TafsirSource.tabary: QuranDBAdapter(TafsirSource.tabary),
    TafsirSource.katheer: QuranDBAdapter(TafsirSource.katheer),
    TafsirSource.baghawy: QuranDBAdapter(TafsirSource.baghawy),
    TafsirSource.saadi: QuranDBAdapter(TafsirSource.saadi),
    TafsirSource.moyassar: QuranDBAdapter(TafsirSource.moyassar),
    TafsirSource.mukhtasar_ar: QuranDBAdapter(TafsirSource.mukhtasar_ar),
    TafsirSource.mukhtasar_en: QuranDBAdapter(TafsirSource.mukhtasar_en),
    TafsirSource.mukhtasar_bn: QuranDBAdapter(TafsirSource.mukhtasar_bn),
    TafsirSource.jalalayn: JalalaynAdapter(),
    TafsirSource.tahrir_wa_tanwir: ExtendedTafsirAdapter("tahrir_wa_tanwir"),
    TafsirSource.qurtubi: ExtendedTafsirAdapter("qurtubi"),
    TafsirSource.kashshaf: ExtendedTafsirAdapter("kashshaf"),
    TafsirSource.mafatih_al_ghayb: ExtendedTafsirAdapter("mafatih_al_ghayb"),
    TafsirSource.mizan: ExtendedTafsirAdapter("mizan"),
    TafsirSource.ruh_al_maani: ExtendedTafsirAdapter("ruh_al_maani"),
    TafsirSource.fath_al_qadir: ExtendedTafsirAdapter("fath_al_qadir"),
    TafsirSource.adwa_al_bayan: ExtendedTafsirAdapter("adwa_al_bayan"),
    TafsirSource.sharawi: ExtendedTafsirAdapter("sharawi"),
    TafsirSource.wasit: ExtendedTafsirAdapter("wasit"),
    TafsirSource.bayani: ExtendedTafsirAdapter("bayani"),
    TafsirSource.fi_zilal: ExtendedTafsirAdapter("fi_zilal"),
    TafsirSource.qushayri: ExtendedTafsirAdapter("qushayri"),
    TafsirSource.ibn_ajiba: ExtendedTafsirAdapter("ibn_ajiba"),
    TafsirSource.nasafi: ExtendedTafsirAdapter("nasafi"),
    TafsirSource.abu_al_saud: ExtendedTafsirAdapter("abu_al_saud"),
    TafsirSource.baydawi: ExtendedTafsirAdapter("baydawi"),
    TafsirSource.khazin: ExtendedTafsirAdapter("khazin"),
    TafsirSource.ibn_juzayy: ExtendedTafsirAdapter("ibn_juzayy"),
    TafsirSource.thalabi: ExtendedTafsirAdapter("thalabi"),
    TafsirSource.mawirdi: ExtendedTafsirAdapter("mawirdi"),
    TafsirSource.samani: ExtendedTafsirAdapter("samani"),
    TafsirSource.raghib_isfahani: ExtendedTafsirAdapter("raghib_isfahani"),
    TafsirSource.ibn_atiyya: ExtendedTafsirAdapter("ibn_atiyya"),
    TafsirSource.zad_al_masir: ExtendedTafsirAdapter("zad_al_masir"),
    TafsirSource.bahr_al_muhit: ExtendedTafsirAdapter("bahr_al_muhit"),
    TafsirSource.samarqandi: ExtendedTafsirAdapter("samarqandi"),
    TafsirSource.ibn_abi_hatim: ExtendedTafsirAdapter("ibn_abi_hatim"),
    TafsirSource.wahidi_wasit: ExtendedTafsirAdapter("wahidi_wasit"),
    TafsirSource.wahidi_wajiz: ExtendedTafsirAdapter("wahidi_wajiz"),
    TafsirSource.izz_bin_abd_salam: ExtendedTafsirAdapter("izz_bin_abd_salam"),
    TafsirSource.ibn_rajab: ExtendedTafsirAdapter("ibn_rajab"),
    TafsirSource.maturidi: ExtendedTafsirAdapter("maturidi"),
    TafsirSource.durr_manthur: ExtendedTafsirAdapter("durr_manthur"),
    TafsirSource.nazm_durar: ExtendedTafsirAdapter("nazm_durar"),
    TafsirSource.ghareeb_quran: ExtendedTafsirAdapter("ghareeb_quran"),
    TafsirSource.gharaib_quran: ExtendedTafsirAdapter("gharaib_quran"),
    TafsirSource.tadhkirat_areeb: ExtendedTafsirAdapter("tadhkirat_areeb"),
    TafsirSource.durr_masun: ExtendedTafsirAdapter("durr_masun"),
    TafsirSource.lubab_ulum: ExtendedTafsirAdapter("lubab_ulum"),
    TafsirSource.manar: ExtendedTafsirAdapter("manar"),
    TafsirSource.safwat: ExtendedTafsirAdapter("safwat"),
    TafsirSource.asbab_nuzul: ExtendedTafsirAdapter("asbab_nuzul"),
    TafsirSource.ayat_ahkam: ExtendedTafsirAdapter("ayat_ahkam"),
    TafsirSource.aysar_jazairi: ExtendedTafsirAdapter("aysar_jazairi"),
    TafsirSource.aysar_homod: ExtendedTafsirAdapter("aysar_homod"),
    TafsirSource.burhan_bahrani: ExtendedTafsirAdapter("burhan_bahrani"),
    TafsirSource.tawilat_najmiyya: ExtendedTafsirAdapter("tawilat_najmiyya"),
    TafsirSource.tibyan_tusi: ExtendedTafsirAdapter("tibyan_tusi"),
    TafsirSource.tabarani: ExtendedTafsirAdapter("tabarani"),
    TafsirSource.ibn_arafa: ExtendedTafsirAdapter("ibn_arafa"),
    TafsirSource.jawahir_thaalbi: ExtendedTafsirAdapter("jawahir_thaalbi"),
    TafsirSource.safi_kashani: ExtendedTafsirAdapter("safi_kashani"),
    TafsirSource.sirat_mustaqim: ExtendedTafsirAdapter("sirat_mustaqim"),
    TafsirSource.muntakhab: ExtendedTafsirAdapter("muntakhab"),
    TafsirSource.nahr_madd: ExtendedTafsirAdapter("nahr_madd"),
    TafsirSource.aaqam: ExtendedTafsirAdapter("aaqam"),
    TafsirSource.jilani: ExtendedTafsirAdapter("jilani"),
    TafsirSource.hubari: ExtendedTafsirAdapter("hubari"),
    TafsirSource.ibn_arabi: ExtendedTafsirAdapter("ibn_arabi"),
    TafsirSource.ibn_abi_zamnin: ExtendedTafsirAdapter("ibn_abi_zamnin"),
    TafsirSource.tustari: ExtendedTafsirAdapter("tustari"),
    TafsirSource.fairuzabadi: ExtendedTafsirAdapter("fairuzabadi"),
    TafsirSource.qummi: ExtendedTafsirAdapter("qummi"),
    TafsirSource.nasai: ExtendedTafsirAdapter("nasai"),
    TafsirSource.hidayah_maki: ExtendedTafsirAdapter("hidayah_maki"),
    TafsirSource.bayan_saadah: ExtendedTafsirAdapter("bayan_saadah"),
    TafsirSource.sufyan_thawri: ExtendedTafsirAdapter("sufyan_thawri"),
    TafsirSource.sadr_mutaallhin: ExtendedTafsirAdapter("sadr_mutaallhin"),
    TafsirSource.abd_razzaq: ExtendedTafsirAdapter("abd_razzaq"),
    TafsirSource.furat_kufi: ExtendedTafsirAdapter("furat_kufi"),
    TafsirSource.hawari: ExtendedTafsirAdapter("hawari"),
    TafsirSource.mujahid: ExtendedTafsirAdapter("mujahid"),
    TafsirSource.taysir_atfiyyish: ExtendedTafsirAdapter("taysir_atfiyyish"),
    TafsirSource.taysir_qattan: ExtendedTafsirAdapter("taysir_qattan"),
    TafsirSource.jawahir_khalili: ExtendedTafsirAdapter("jawahir_khalili"),
    TafsirSource.hashiyat_sawi: ExtendedTafsirAdapter("hashiyat_sawi"),
    TafsirSource.haqaiq_sulami: ExtendedTafsirAdapter("haqaiq_sulami"),
    TafsirSource.rumuz_kunuz: ExtendedTafsirAdapter("rumuz_kunuz"),
    TafsirSource.ruh_bayan: ExtendedTafsirAdapter("ruh_bayan"),
    TafsirSource.araais_bayan: ExtendedTafsirAdapter("araais_bayan"),
    TafsirSource.nuzhat_qulub: ExtendedTafsirAdapter("nuzhat_qulub"),
    TafsirSource.majma_bayan: ExtendedTafsirAdapter("majma_bayan"),
    TafsirSource.mahasin_tawil: ExtendedTafsirAdapter("mahasin_tawil"),
    TafsirSource.mukhtasar_katheer: ExtendedTafsirAdapter("mukhtasar_katheer"),
    TafsirSource.muqatil: ExtendedTafsirAdapter("muqatil"),
    TafsirSource.himyan_zad: ExtendedTafsirAdapter("himyan_zad"),
}

__all__ = ["TafsirAdapter", "ADAPTERS"]
