"""Adapter for the 86 extended tafsirs stored across 4 sharded DB files.

Each shard is ~260 MB (instead of a single 1 GB file) to stay within
Render's 512 MB RAM limit.  The SOURCE_TO_SHARD mapping determines which
shard file to open for each tafsir source.
"""

import sqlite3
from pathlib import Path

from tafsir.adapters.base import TafsirAdapter
from tafsir.db import QuranDataError
from tafsir.data_loader import get_extended_shard_path


# ── Source → shard mapping (auto-generated by split_db.py) ────────────────────

SOURCE_TO_SHARD = {
    "asbab_nuzul": "extended_tafsir_s1.db",
    "aysar_homod": "extended_tafsir_s1.db",
    "aysar_jazairi": "extended_tafsir_s1.db",
    "bayan_saadah": "extended_tafsir_s1.db",
    "burhan_bahrani": "extended_tafsir_s1.db",
    "ibn_juzayy": "extended_tafsir_s1.db",
    "ibn_rajab": "extended_tafsir_s1.db",
    "jawahir_thaalbi": "extended_tafsir_s1.db",
    "khazin": "extended_tafsir_s1.db",
    "lubab_ulum": "extended_tafsir_s1.db",
    "mafatih_al_ghayb": "extended_tafsir_s1.db",
    "manar": "extended_tafsir_s1.db",
    "mawirdi": "extended_tafsir_s1.db",
    "mukhtasar_katheer": "extended_tafsir_s1.db",
    "qurtubi": "extended_tafsir_s1.db",
    "raghib_isfahani": "extended_tafsir_s1.db",
    "safi_kashani": "extended_tafsir_s1.db",
    "tabarani": "extended_tafsir_s1.db",
    "tadhkirat_areeb": "extended_tafsir_s1.db",
    "taysir_atfiyyish": "extended_tafsir_s1.db",
    "wahidi_wajiz": "extended_tafsir_s1.db",
    "aaqam": "extended_tafsir_s2.db",
    "durr_masun": "extended_tafsir_s2.db",
    "fi_zilal": "extended_tafsir_s2.db",
    "hashiyat_sawi": "extended_tafsir_s2.db",
    "hawari": "extended_tafsir_s2.db",
    "hidayah_maki": "extended_tafsir_s2.db",
    "hubari": "extended_tafsir_s2.db",
    "ibn_arabi": "extended_tafsir_s2.db",
    "ibn_arafa": "extended_tafsir_s2.db",
    "ibn_atiyya": "extended_tafsir_s2.db",
    "jawahir_khalili": "extended_tafsir_s2.db",
    "kashshaf": "extended_tafsir_s2.db",
    "mahasin_tawil": "extended_tafsir_s2.db",
    "majma_bayan": "extended_tafsir_s2.db",
    "mizan": "extended_tafsir_s2.db",
    "mujahid": "extended_tafsir_s2.db",
    "muntakhab": "extended_tafsir_s2.db",
    "muqatil": "extended_tafsir_s2.db",
    "nuzhat_qulub": "extended_tafsir_s2.db",
    "ruh_bayan": "extended_tafsir_s2.db",
    "samarqandi": "extended_tafsir_s2.db",
    "wasit": "extended_tafsir_s2.db",
    "adwa_al_bayan": "extended_tafsir_s3.db",
    "durr_manthur": "extended_tafsir_s3.db",
    "fairuzabadi": "extended_tafsir_s3.db",
    "ghareeb_quran": "extended_tafsir_s3.db",
    "haqaiq_sulami": "extended_tafsir_s3.db",
    "ibn_abi_zamnin": "extended_tafsir_s3.db",
    "ibn_ajiba": "extended_tafsir_s3.db",
    "izz_bin_abd_salam": "extended_tafsir_s3.db",
    "nahr_madd": "extended_tafsir_s3.db",
    "nasafi": "extended_tafsir_s3.db",
    "nasai": "extended_tafsir_s3.db",
    "nazm_durar": "extended_tafsir_s3.db",
    "qummi": "extended_tafsir_s3.db",
    "ruh_al_maani": "extended_tafsir_s3.db",
    "safwat": "extended_tafsir_s3.db",
    "sharawi": "extended_tafsir_s3.db",
    "sirat_mustaqim": "extended_tafsir_s3.db",
    "tawilat_najmiyya": "extended_tafsir_s3.db",
    "taysir_qattan": "extended_tafsir_s3.db",
    "tibyan_tusi": "extended_tafsir_s3.db",
    "zad_al_masir": "extended_tafsir_s3.db",
    "abd_razzaq": "extended_tafsir_s4.db",
    "abu_al_saud": "extended_tafsir_s4.db",
    "araais_bayan": "extended_tafsir_s4.db",
    "ayat_ahkam": "extended_tafsir_s4.db",
    "bahr_al_muhit": "extended_tafsir_s4.db",
    "bayani": "extended_tafsir_s4.db",
    "baydawi": "extended_tafsir_s4.db",
    "fath_al_qadir": "extended_tafsir_s4.db",
    "furat_kufi": "extended_tafsir_s4.db",
    "gharaib_quran": "extended_tafsir_s4.db",
    "himyan_zad": "extended_tafsir_s4.db",
    "ibn_abi_hatim": "extended_tafsir_s4.db",
    "jilani": "extended_tafsir_s4.db",
    "maturidi": "extended_tafsir_s4.db",
    "qushayri": "extended_tafsir_s4.db",
    "rumuz_kunuz": "extended_tafsir_s4.db",
    "sadr_mutaallhin": "extended_tafsir_s4.db",
    "sufyan_thawri": "extended_tafsir_s4.db",
    "tahrir_wa_tanwir": "extended_tafsir_s4.db",
    "thalabi": "extended_tafsir_s4.db",
    "tustari": "extended_tafsir_s4.db",
    "wahidi_wasit": "extended_tafsir_s4.db",
}

# Unique shard filenames for iteration
SHARD_FILES = sorted(set(SOURCE_TO_SHARD.values()))


def _escape_like(text: str) -> str:
    return text.replace("!", "!!").replace("%", "!%").replace("_", "!_")


def _open_shard(db_path: Path) -> sqlite3.Connection | None:
    """Open a shard DB with memory-optimised PRAGMAs."""
    if not db_path.exists():
        return None
    uri = f"file:{db_path}?mode=ro"
    conn = sqlite3.connect(uri, uri=True, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA query_only = ON")
    conn.execute("PRAGMA cache_size = -1000")   # 1 MB page cache (minimal)
    conn.execute("PRAGMA mmap_size = 0")        # Disable memory-mapped I/O
    conn.execute("PRAGMA temp_store = FILE")     # Use disk for temp
    return conn


class ExtendedTafsirAdapter(TafsirAdapter):
    """Reads tafsir content from the sharded extended_tafsir DBs.

    Schema: tafsir_content(source TEXT, surah INT, ayah INT, text TEXT)
    """

    def __init__(self, source: str):
        self.source = source
        self._shard_file = SOURCE_TO_SHARD.get(source)

    def _get_conn(self) -> sqlite3.Connection | None:
        if not self._shard_file:
            return None
        db_path = get_extended_shard_path(self._shard_file)
        return _open_shard(db_path)

    def fetch(self, surah: int, ayah: int) -> str | None:
        conn = self._get_conn()
        if conn is None:
            return None
        try:
            row = conn.execute(
                "SELECT text FROM tafsir_content WHERE source = ? AND surah = ? AND ayah = ?",
                (self.source, surah, ayah),
            ).fetchone()
            return row["text"] if row else None
        except sqlite3.DatabaseError as exc:
            raise QuranDataError(f"خطأ في الاستعلام عن {self.source}: {exc}") from exc
        finally:
            conn.close()

    def search(self, query: str, surah_filter: list[int] | None = None, limit: int = 20) -> list[dict]:
        conn = self._get_conn()
        if conn is None:
            return []
        escaped = _escape_like(query.strip())
        like_param = f"%{escaped}%"
        try:
            if surah_filter:
                placeholders = ",".join("?" * len(surah_filter))
                sql = (
                    f"SELECT surah, ayah, text FROM tafsir_content"
                    f" WHERE source = ? AND text LIKE ? ESCAPE '!'"
                    f" AND surah IN ({placeholders}) LIMIT ?"
                )
                params = (self.source, like_param, *surah_filter, limit)
            else:
                sql = (
                    "SELECT surah, ayah, text FROM tafsir_content"
                    " WHERE source = ? AND text LIKE ? ESCAPE '!' LIMIT ?"
                )
                params = (self.source, like_param, limit)
            rows = conn.execute(sql, params).fetchall()
            return [{"surah": r["surah"], "ayah": r["ayah"], "text": r["text"]} for r in rows]
        except sqlite3.DatabaseError as exc:
            raise QuranDataError(f"خطأ في البحث في {self.source}: {exc}") from exc
        finally:
            conn.close()
